### ISSUE TITLE
Add ADIOS 2 -  proposal

### ISSUE THREAD

**Issue by IgorBaratta** [fem-on-colab/fem-on-colab#18]
To visualise high order functions in FEniCSx, ADIOS2 writers are recommended, specially the `VTXWriter`, which is used in many demos now.
Then If ADIOS 2 is available in the system and detected by dolfinx, `VTXWriter` then becomes available.

In case you think it's interesting to have it I can try to add a script to install adios 2.

Link to the documentation:
https://adios2.readthedocs.io/en/latest/

**Comment by francesco-ballarin** [comment]
Cool, it should be doable for me to install ADIOS2 alongside dolfinx. 

Should I just make something similar to this
https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile#L217
?

Shall I take one of these tests
https://github.com/FEniCS/dolfinx/blob/main/python/test/unit/io/test_adios2.py
to check that ADIOS2 writer works correctly, or would you suggest anything else?

**Comment by francesco-ballarin** [comment]
An updated package with ADIOS2 support was released.

Can you check if
https://github.com/fem-on-colab/fem-on-colab/compare/main...adios
makes sense?

I ran the updated test 
https://colab.research.google.com/github/fem-on-colab/fem-on-colab.github.io/blob/gh-pages/tests/fenicsx/test-dolfinx.ipynb
on an actual colab instance and I confirm that VTXWriter is now available. I can see a new folder "solution.bp" being created, zip it, download it and uncompress it. However, I don't understand how to open that in paraview.

I will wait merging until I can test this also for the twin project on Kaggle
(can't do that now due to https://github.com/Kaggle/docker-python/issues/1205)
This in particular will mean that the package I prepared today we will soon be overwritten by the one coming from a scheduled run on Saturday (based on main), so VTXWriter support may temporarily disappear (unless the adios branch gets merged in tomorrow)

**Comment by IgorBaratta** [comment]
Hi @francesco-ballarin , 
Thanks for your quick reply.

> Can you check if [main...adios](https://github.com/fem-on-colab/fem-on-colab/compare/main...adios) makes sense?

I think it makes sense and it seems to be working well for me.




> However, I don't understand how to open that in paraview.

I think you need version > 5.10 to open `bp` files. I'm currently using paraview version 5.11.0, and so I can select the ADIOSVTXReader on paraview.

**Comment by francesco-ballarin** [comment]
Thanks @IgorBaratta IgorBaratta

> to open bp files

Are they files or folders? What confuses me is that on colab a folder gets created, rather than a file.

> I think you need version > 5.10 

I have 5.11.0-RC1 (pacakged by debian)

**Comment by francesco-ballarin** [comment]
Hi @IgorBaratta ,
I confirm that I have also tested the branch on the Kaggle installation scripts.

Both on Colab and Kaggle the solution gets exported as a bp folder, rather than bp file. Let me know if that is correct or, if not, if this is anything that you have ever seen before, or might be an error in the configuration options.

**Comment by IgorBaratta** [comment]
Hi, sorry for the delay.
This is correct.

With the latest paraview:

```
paraview  output.bp
```

Works fine for me, even if it looks like a folder.

**Comment by francesco-ballarin** [comment]
Great. I've merged to main, future weekly builds of FEniCSx will include ADIOS.
