### ISSUE TITLE
Firedrake missing pyrsistent module?

### ISSUE THREAD

**Issue by ScottMacLachlan** [fem-on-colab/fem-on-colab#27]
Upon trying to run 
```
try:
    import firedrake
except ImportError:
    !wget "https://fem-on-colab.github.io/releases/firedrake-install-real.sh" -O "/tmp/firedrake-install.sh" && bash "/tmp/firedrake-install.sh"
    import firedrake
```
in a new colab notebook today, I receive messages as if everything has worked correctly, but then the error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0a5993fa81f2> in <cell line: 1>()
      1 try:
----> 2     import firedrake
      3 except ImportError:

ModuleNotFoundError: No module named 'firedrake'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
6 frames
/usr/local/lib/python3.10/dist-packages/loopy/translation_unit.py in <module>
     37 from loopy.tools import update_persistent_hash
     38 from pymbolic.primitives import Call
---> 39 from pyrsistent import pmap, PMap
     40 
     41 __doc__ = """

ModuleNotFoundError: No module named 'pyrsistent'

---------------------------------------------------------------------------
```

Has something changed in the setup to prompt this?  Many thanks!

**Comment by ScottMacLachlan** [comment]
Adding
```
!pip install pyrsistent
```
Does the expected, allowing the import to complete

**Comment by francesco-ballarin** [comment]
Thanks for reporting this, I tracked it down!

The base image on GitHub actions gets updated monthly, i.e. the latest update happened on August 1.
In the meantime there is a commit
https://github.com/googlecolab/backend-info/commit/a60c6ebe916641373773e89ea2cff672d42c34fa
dated August 9 that removes pyrsistent from the default Colab runtime.

The latest firedrake build happened last Saturday, i.e. August 12, based on the base image of August 1.
Since that base image contains `pyrsistent`, the line
https://github.com/firedrakeproject/loopy/blob/main/setup.py#L99C12-L99C22
has no effect because `pyrsistent` is already there on the base image.

The fix is "simple". I'll manually trigger a base image build, rather than waiting for the next month, to bring the base image up to date. This in turn will trigger an update of all dependencies (`PETSc` in particular), and finally an update of `firedrake` itself. It will take CI a few hours to build the entire dependency chain, I'll keep this open in the meantime.

**Comment by francesco-ballarin** [comment]
Hi @ScottMacLachlan ,
this is now fixed.

`firedrake` now works without any additional `pip install pyrsistent`.
`fireshape` will also be fixed with https://github.com/fireshape/fireshape/pull/78

**Comment by ScottMacLachlan** [comment]
Wonderful - many thanks for the quick fix!
