### ISSUE TITLE
firedrake with netgen

### ISSUE THREAD

**Issue by cpraveen** [fem-on-colab/fem-on-colab#36]
Hello, thank you very much for this project which is great for teaching. 

I think firedrake is not compiled with netgen support. Is it possible to include netgen support within firedrake ?

**Comment by francesco-ballarin** [comment]
Can you provide a minimal example that leads to you to say that "firedrake is not compiled with netgen support"?

It's true that since https://github.com/viskex/viskex/commit/3ddffdaaa3d2983c77bec45d09816961371c07b8 happened I currently don't have any test about firderake + netgen (only testing them separately), but there have been people (cc @UZerbinati and his collaborators) who have used firderake + netgen on Colab in the past.

Keep in mind that you _must_ install netgen _before_ firedrake for firedrake to be able to detect netgen on import.

**Comment by cpraveen** [comment]
Thank you for your answer. That was the mistake i made, now installing netgen before firedrake and it works fine.
