### ISSUE TITLE
Looks like "webgui_jupyter_widgets" module from NGSolve is broken

### ISSUE THREAD

**Issue by pengliu-Ottawa** [fem-on-colab/fem-on-colab#7]
Hi, 

Thanks for your hard work of making moat FEM pakages working on Colab. a life saver...

When I am trying NGSolve , looks like the web display module is somehow not there.
![image](https://user-images.githubusercontent.com/61391211/136103411-ce88f155-d3fe-489f-be0d-727e0531e22c.png)

Peng

**Comment by francesco-ballarin** [comment]
This issue has been fixed in the updated ngsolve package. `ngsolve.webgui.Draw` is tested in the newly introduced test notebook at https://colab.research.google.com/github/fem-on-colab/fem-on-colab/blob/main/ngsolve/test-ngsolve-mpl.ipynb. Such notebook will soon be linked to our packages page https://fem-on-colab.github.io/packages.html

Feel free to re-open if further issues arise.
