### ISSUE TITLE
Maintenance in progress: packages may be temporarily unavailable

### ISSUE THREAD

**Issue by francesco-ballarin** [fem-on-colab/fem-on-colab#8]
Today I will be carrying out a maintenance operation on the repository that may temporarily break the download of existing packages. The planned tasks during the maintenance are the following:
- update Colab base image as of January 2022
- support real and complex PETSc scalar types
- provide versioning in package install files on the website, so that carrying out a similar maintenance operation in future will hopefully be less intrusive on end users.

The issue will be closed when the maintenance operation is concluded.

**Current status** (Last update: Sun Jan 9 20:00:00 2022 +0100)
- `FEniCS`: ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+) available (real scalar type only), maintenance completed
- `FEniCSx`: ![#f03c15](https://via.placeholder.com/15/c5f015/000000?text=+) available (real and complex scalar types), maintenance completed
- `firedrake`: ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+) available (real and complex scalar types), maintenance completed
- `gmsh`: ![#f03c15](https://via.placeholder.com/15/c5f015/000000?text=+) available, maintenance completed
- `ngsolve`: ![#f03c15](https://via.placeholder.com/15/c5f015/000000?text=+) available, maintenance completed

**Comment by marco-fedele** [comment]
Dear @francesco-ballarin ,

In a course that I teach I am using the fantastic FEM on colab packages to install FEniCS. 

The problem is that we have the exam (using FEniCS on colab) on Monday and now the installation is not working anymore.

Do you have a backup of the working packages?

The command that is not working anymore is:

`!wget "https://fem-on-colab.github.io/releases/fenics-install.sh" -O "/tmp/fenics-install.sh" && bash "/tmp/fenics-install.sh"
    import dolfin as df  `

Thanks in advance!

Marco

**Comment by francesco-ballarin** [comment]
Ciao Marco e grazie, @marco-fedele

FEniCS is building right now and should be up again in the afternoon. 

Indeed the `provide versioning in package install files on the website` improvement was aiming at avoiding downtime for MSc/PhD courses. Further details on this will be posted on the website after the maintenance is completed.

Apologies for the inconvenience

**Comment by marco-fedele** [comment]
Grazie mille Francesco!

I really appreciate the effort you made for this repository.

**Comment by marc-git** [comment]
Hi Francesco, it seems like it is running much slower now. Maybe only running on one core ? How would you check this ? I am using MUMPS

**Comment by francesco-ballarin** [comment]
@marc-git which package are you using? Can you share (privately to my email address, if needed) a notebook to reproduce this, with an indication of which part have gotten slower?

**Comment by francesco-ballarin** [comment]
Maintenance is completed. We will investigate the issue reported by @marc-git and, if appropriate, a new issue will be opened.

**Comment by marc-git** [comment]
Using 

`"https://fem-on-colab.github.io/releases/fenics-install.sh"`

Hi Francesco, I have a deadline coming up so I can't do much right now.  I am using non-linear solver and, since the size is greater than 4GB, I use the mumps package to solve rather than the default UMFPACK.  Previously these problems solved much faster in Colab than on my machine. My subjective impression is that now this has reversed. My Macbook Pro 14,3 solves faster than colab. But I am not solving the same problems so comparing is difficult.  I wonder how we can check if it is running on multiple cores or not.  On my desktop machine running linux I can't get it to go parallel so maybe this is related.

**Comment by francesco-ballarin** [comment]
Unless you do something special (e.g., use `ipyparallel`, but I have never tried it with Colab), I guess that it is running on a single core.

If the problem was the same, a meaningful way to compare before & after the update would probably be to have `ksp_view` print details of the MUMPS options. It is very much possible that the culprit is not the upgrade of the FEniCS package itself, but the fact that I had updated PETSc as well (which, in turn, may have shipped a newer MUMPS version, which may come with different default options).

Feel free to get in touch with me via email in future if you are willing to debug this any further.
